### PR TITLE
Neighbourlist

### PR DESCRIPTION
**Pull request by harmening**

### CODE REVIEW

**Comment by hnargos** [comment]
For loops are very inefficient in python. This amount of nested loops is slow, very very slow.
Did you test that for a couple of configurations and measured the time?

**Comment by harmening** [comment]
Yes, you're right. And I just got an idea for an improvement. going to implement it tomorrow!

**Comment by hnargos** [comment]
Oh and could you please return not only the indices but also the absolut distances in the same format? Just replacing the list of particle indices with the absolut distances that you have to calculate anyway?

Example:
neighborlist
1 : [2,3]
2 : [1,3]
3 : [1,2]
if 1,2,3 are the indices of each particle and [ ] is the index of the particle in reach 
=>
1: [np.linalg.norm(r1-r2), np.linalg.norm(r1-r3)]
2: [np.linalg.norm(r2-r1), np.linalg.norm(r2-r3)]
3: [np.linalg.norm(r3-r1), np.linalg.norm(r3-r2)]
I am not sure wether it is r1-r2 or r2-r1 but you are calculating them in your algorithm.

**Comment by harmening** [comment]
In a second dictionary or attached to the first one?

**Comment by hnargos** [comment]
In a second one. So you would return eg
"return neighbors, dr"

**Review by skieninger — COMMENTED** [review]
To resolve one of the merge conflicts move function compute_neighbourlists above/below the other function. Currently it's written inside the function naive_dists

**Comment by harmening** [comment]
you can merge it now! :-)

**Pull request merged**
