### PR TITLE
Ewald sum

### PR DESCRIPTION
**Pull request by hnargos**
I moved the functions from the extra file to interaction_particles.py .
Updated the documentation for the functions.

### CODE REVIEW

**Review by Dr-Manni — COMMENTED** [review]
looks good! 
Theres one thing confusing me though:
In the docstring of __short_range_potential

why does it say:
" PROTOTYP coulomb
__short_range_potential(...) "
What do you mean with Protoyp [sic] ? and why do you repeat the functions name and input in the dosctring ???

**Comment by hnargos** [comment]
The PROTOTYP part means to me that I still have to do extensiv tests and
also that it is not yet refined to be fast or efficient.
I repeat the functions name and input in the docstring to give someone who
calls that help/docstring an immediate information about the
possible/required variables. Because if you call the function information
with tab you can usually see only the first couple of lines, this way it
is easy to know what to feed the function.

**Review by Dr-Manni — COMMENTED** [review]
you dont't need variance as an input for __short_range potential. It is already initialiezd with the coulomb object, we call it std (because its the standart deviation and not the variance of the function) 
so please replace "variance" with "self.std"

**Comment by hnargos** [comment]
Oh, good point.
fixed

**Pull request merged**
